name: Primary

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    if: ${{ success()}}
    steps:
      - name: Do something
        run: |
          echo "Hello World"
          env
