name: Primary

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo "Hello World"
          env

  secondary:
    uses: ./.github/workflows/secondary.yml
    needs: do-something
    if: ${{ always() }}
