name: Primary

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          whoami

          echo "Hello, world!" > file

          echo $UID
          echo $GID

          cat /etc/passwd

  secondary:
    uses: ./.github/workflows/secondary.yml
    needs: do-something
    if: ${{ always() }}
