name: Secondary

on:
  workflow_dispatch:
  workflow_call:

jobs:
  do-something:
    runs-on: ubuntu-latest
    if: ${{ success()}}
    steps:
      - name: Do something
        run: |
          whoami
          cat /etc/passwd

  alwaysRun:
    needs: do-something
    runs-on: ubuntu-latest
    if: ${{ always()}}
    steps:
      - name: Always run
        run: |
          echo "Always run"
