name: Secondary

on:
  workflow_dispatch:
  workflow_call:

jobs:
  do-something:
    runs-on: ubuntu-latest
    if: ${{ success()}}
    steps:
      - name: Do something
        run: |
          echo "Hello World"
          env
